/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtmosferaRouteImport } from './routes/atmosfera'
import { Route as EarthquakesRouteImport } from './routes/earthquakes'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LiveRouteImport } from './routes/live'
import { Route as NaturalEventsRouteImport } from './routes/natural-events'
import { Route as OceanoRouteImport } from './routes/oceano'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WeatherRouteImport } from './routes/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmosferaRoute = AtmosferaRouteImport.update({
  id: '/atmosfera',
  path: '/atmosfera',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthquakesRoute = EarthquakesRouteImport.update({
  id: '/earthquakes',
  path: '/earthquakes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturalEventsRoute = NaturalEventsRouteImport.update({
  id: '/natural-events',
  path: '/natural-events',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanoRoute = OceanoRouteImport.update({
  id: '/oceano',
  path: '/oceano',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atmosfera': typeof AtmosferaRoute
  '/earthquakes': typeof EarthquakesRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/live': typeof LiveRoute
  '/natural-events': typeof NaturalEventsRoute
  '/oceano': typeof OceanoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/timeline': typeof TimelineRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atmosfera': typeof AtmosferaRoute
  '/earthquakes': typeof EarthquakesRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/live': typeof LiveRoute
  '/natural-events': typeof NaturalEventsRoute
  '/oceano': typeof OceanoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/timeline': typeof TimelineRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atmosfera': typeof AtmosferaRoute
  '/earthquakes': typeof EarthquakesRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/live': typeof LiveRoute
  '/natural-events': typeof NaturalEventsRoute
  '/oceano': typeof OceanoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/timeline': typeof TimelineRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atmosfera'
    | '/earthquakes'
    | '/eventos'
    | '/explorar'
    | '/live'
    | '/natural-events'
    | '/oceano'
    | '/sitemap.xml'
    | '/sobre'
    | '/timeline'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atmosfera'
    | '/earthquakes'
    | '/eventos'
    | '/explorar'
    | '/live'
    | '/natural-events'
    | '/oceano'
    | '/sitemap.xml'
    | '/sobre'
    | '/timeline'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/atmosfera'
    | '/earthquakes'
    | '/eventos'
    | '/explorar'
    | '/live'
    | '/natural-events'
    | '/oceano'
    | '/sitemap.xml'
    | '/sobre'
    | '/timeline'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtmosferaRoute: typeof AtmosferaRoute
  EarthquakesRoute: typeof EarthquakesRoute
  EventosRoute: typeof EventosRoute
  ExplorarRoute: typeof ExplorarRoute
  LiveRoute: typeof LiveRoute
  NaturalEventsRoute: typeof NaturalEventsRoute
  OceanoRoute: typeof OceanoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TimelineRoute: typeof TimelineRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atmosfera': {
      id: '/atmosfera'
      path: '/atmosfera'
      fullPath: '/atmosfera'
      preLoaderRoute: typeof AtmosferaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earthquakes': {
      id: '/earthquakes'
      path: '/earthquakes'
      fullPath: '/earthquakes'
      preLoaderRoute: typeof EarthquakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natural-events': {
      id: '/natural-events'
      path: '/natural-events'
      fullPath: '/natural-events'
      preLoaderRoute: typeof NaturalEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oceano': {
      id: '/oceano'
      path: '/oceano'
      fullPath: '/oceano'
      preLoaderRoute: typeof OceanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtmosferaRoute: AtmosferaRoute,
  EarthquakesRoute: EarthquakesRoute,
  EventosRoute: EventosRoute,
  ExplorarRoute: ExplorarRoute,
  LiveRoute: LiveRoute,
  NaturalEventsRoute: NaturalEventsRoute,
  OceanoRoute: OceanoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TimelineRoute: TimelineRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
